# Generated by Django 6.0 on 2025-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about',
            field=models.TextField(default='About coming soon'),
        ),
    ]
