# Generated by Django 6.0 on 2025-12-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='About coming soon')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='about',
        ),
    ]
