# Generated by Django 6.0 on 2025-12-26 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about_remove_blog_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_description',
            field=models.TextField(default='no description allowed', max_length=2555),
        ),
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
